// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGOy1tCGZjdUtNJNj8VcEmpCCDC9KBC4',
    appId: '1:606903143656:web:21481a618f2dd4e0150d5d',
    messagingSenderId: '606903143656',
    projectId: 'avalia-ubs',
    authDomain: 'avalia-ubs.firebaseapp.com',
    storageBucket: 'avalia-ubs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwAFZwU6n_Jos0D-rGHOFsVQPpOPVXSQ',
    appId: '1:606903143656:android:2bb371851fa0507a150d5d',
    messagingSenderId: '606903143656',
    projectId: 'avalia-ubs',
    storageBucket: 'avalia-ubs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIF2lRWaa1qtxUCBT0ykXrtCh-YPNMsoQ',
    appId: '1:606903143656:ios:0c1036f2214523e2150d5d',
    messagingSenderId: '606903143656',
    projectId: 'avalia-ubs',
    storageBucket: 'avalia-ubs.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIF2lRWaa1qtxUCBT0ykXrtCh-YPNMsoQ',
    appId: '1:606903143656:ios:0c1036f2214523e2150d5d',
    messagingSenderId: '606903143656',
    projectId: 'avalia-ubs',
    storageBucket: 'avalia-ubs.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLuScvvrdZW9MyMlYFbMPiCHS3AGI0Tvk',
    appId: '1:606903143656:web:2b512f978fc33229150d5d',
    messagingSenderId: '606903143656',
    projectId: 'avalia-ubs',
    authDomain: 'avalia-ubs.firebaseapp.com',
    storageBucket: 'avalia-ubs.firebasestorage.app',
  );
}
